# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: uuidmasterapi-db-1
    hostname: uuidmasterapi-db-1
    ports:
      - "1433:1433" # Publishes the port to docker host in order to access db from vscode extension. 
    environment:
      - SA_PASSWORD=Student1
      - ACCEPT_EULA=Y
    networks:
      - uuidmasterapi
    volumes:
      - db_data:/var/opt/mssql
  api:
    depends_on:
      - db
    image: uuidmasterapi:dev
    build:
      context: ./UuidMasterApi
      dockerfile: Dockerfile
    ports: # replace by expose
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - uuidmasterapi
  # reverseproxy:
  #   depends_on:
  #     - api
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - uuidmasterapi
  
  # specify rabbitmq

networks:
  uuidmasterapi:
    name: uuidmasterapi
    driver: bridge
volumes:
  db_data:
