# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Student1
      - ACCEPT_EULA=Y
    volumes:
      - sqlvolume:/var/opt/mssql
  api:
    depends_on:
      - db
    image: uuidmasterapi:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
      # - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - uuidmasterapi

networks:
  uuidmasterapi:
    driver: bridge
volumes:
  sqlvolume:
