// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UuidMasterApi;

#nullable disable

namespace UuidMasterApi.Migrations
{
    [DbContext(typeof(UuidMasterApiDbContext))]
    [Migration("20220510084455_InitialSeed")]
    partial class InitialSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UuidMasterApi.Entities.Resource", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EntityVersion")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("SourceEntityId")
                        .HasColumnType("int");

                    b.HasKey("Uuid");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("1a908081-21d3-4f28-952d-584f4490b3a8"),
                            EntityType = "user",
                            EntityVersion = 1,
                            Source = "FrontEnd",
                            SourceEntityId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
