// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UuidMasterApi;

#nullable disable

namespace UuidMasterApi.Migrations
{
    [DbContext(typeof(UuidMasterApiDbContext))]
    partial class UuidMasterApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("UuidMasterApi.Entities.Resource", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("EntityVersion")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<decimal>("SourceEntityId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Uuid");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Uuid = new Guid("fed92226-4b82-47da-a0e5-85855faa9a17"),
                            EntityType = "user",
                            EntityVersion = 1m,
                            Source = 2,
                            SourceEntityId = 1m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
